<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260608060705 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Etap 1.3: encja MailAccount + many-to-many User <-> MailAccount';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE mail_account (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label VARCHAR(255) NOT NULL, host VARCHAR(255) NOT NULL, port INT NOT NULL, imap_login VARCHAR(255) NOT NULL, folder VARCHAR(255) NOT NULL, auth_type VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE mail_account_user (mail_account_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (mail_account_id, user_id))');
        $this->addSql('CREATE INDEX IDX_F9D620F74FA8B546 ON mail_account_user (mail_account_id)');
        $this->addSql('CREATE INDEX IDX_F9D620F7A76ED395 ON mail_account_user (user_id)');
        $this->addSql('ALTER TABLE mail_account_user ADD CONSTRAINT FK_F9D620F74FA8B546 FOREIGN KEY (mail_account_id) REFERENCES mail_account (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE mail_account_user ADD CONSTRAINT FK_F9D620F7A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE mail_account_user DROP CONSTRAINT FK_F9D620F74FA8B546');
        $this->addSql('ALTER TABLE mail_account_user DROP CONSTRAINT FK_F9D620F7A76ED395');
        $this->addSql('DROP TABLE mail_account');
        $this->addSql('DROP TABLE mail_account_user');
    }
}
