<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260616083556 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Etap 3.1: encje Message + Attachment (indeks archiwum). '
            . 'Idempotencja UNIQUE(account_id, sha256); attachment ON DELETE CASCADE; '
            . 'message->mail_account bez cascade (guard przed kasowaniem konta z mailami).';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE attachment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, filename VARCHAR(255) DEFAULT NULL, mime_type VARCHAR(255) DEFAULT NULL, size INT DEFAULT NULL, sha256 VARCHAR(64) DEFAULT NULL, message_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_795FD9BB537A1329 ON attachment (message_id)');
        $this->addSql('CREATE TABLE message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, folder VARCHAR(255) NOT NULL, message_id VARCHAR(255) DEFAULT NULL, subject TEXT DEFAULT NULL, from_name VARCHAR(255) DEFAULT NULL, from_email VARCHAR(255) DEFAULT NULL, sent_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, size INT NOT NULL, sha256 VARCHAR(64) NOT NULL, has_attachments BOOLEAN NOT NULL, verified BOOLEAN NOT NULL, archive_path VARCHAR(255) NOT NULL, body TEXT DEFAULT NULL, imap_uid INT DEFAULT NULL, account_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B6BD307F9B6B5FBA ON message (account_id)');
        $this->addSql('CREATE INDEX idx_message_message_id ON message (message_id)');
        $this->addSql('CREATE INDEX idx_message_account_date ON message (account_id, sent_at)');
        $this->addSql('CREATE UNIQUE INDEX uniq_message_account_sha256 ON message (account_id, sha256)');
        $this->addSql('ALTER TABLE attachment ADD CONSTRAINT FK_795FD9BB537A1329 FOREIGN KEY (message_id) REFERENCES message (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F9B6B5FBA FOREIGN KEY (account_id) REFERENCES mail_account (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE attachment DROP CONSTRAINT FK_795FD9BB537A1329');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307F9B6B5FBA');
        $this->addSql('DROP TABLE attachment');
        $this->addSql('DROP TABLE message');
    }
}
